### ISSUE TITLE
Api Whale Alert

### ISSUE THREAD

**Issue by Satosh1Nakamot0** [curly60e/pyblock#107]
La API de Whale Alert le permite recuperar datos de transacciones en vivo e históricos de la principal cadena de bloques de Bitcoin.

Para el plan gratuito, el número de solicitudes está limitado a 10 por minuto.

Enlace https://api.whale-alert.io/v1

**Comment by curly60e** [comment]
Perfecto, voy a intentar agregar eso, vamos a dejarlo pendiente como mejora

**Comment by Satosh1Nakamot0** [comment]
12 months ☣️

**Comment by Satosh1Nakamot0** [comment]
✓
