### ISSUE TITLE
URI y LNDConnect - Qr Ascii en Menú Lightning

### ISSUE THREAD

**Issue by Satosh1Nakamot0** [curly60e/pyblock#116]
- N. Get Node Info - Mostrar URI Qr Ascii. 

        	 NODE INFORMATION
        Version: 
        Node ID: 
        Alias: 
        Color: #
        Pending Channels: 
        Active Channels: 
        Inactive Channels: 
        Peers: 
        URI: [pubkey@host:port]
        URI Qr Ascii. 
       
        
-  L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

**Comment by curly60e** [comment]
Tengo que chequear si se puede hacer eso con el nodo.

**Comment by Satosh1Nakamot0** [comment]
L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

**Comment by Satosh1Nakamot0** [comment]
L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

**Comment by Satosh1Nakamot0** [comment]
L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

**Comment by Satosh1Nakamot0** [comment]
L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

**Comment by Satosh1Nakamot0** [comment]
L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

Generate a QRCode or URI to connect applications to lnd instances.

lndconnect://<host>:<port>?[cert=<base64url DER certifcate>&]macaroon=<base64url macaroon>

Create and show a QR code using command line

This is useful when one doesn't want to bring dependencies.

echo 'lndconnect://example.com?cert='"`grep -v 'CERTIFICATE' tls.cert | tr -d '=' | tr '/+' '_-'`"'&macaroon='"`base64 admin.macaroon | tr -d '=' | tr '/+' '_-'`" | tr -d '\n' | qrencode -o /tmp/out.png

**Comment by Satosh1Nakamot0** [comment]
L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

Generate a QRCode or URI to connect applications to lnd instances.

lndconnect://<host>:<port>?[cert=<base64url DER certifcate>&]macaroon=<base64url macaroon>

Create and show a QR code using command line

This is useful when one doesn't want to bring dependencies.

echo 'lndconnect://example.com?cert='"`grep -v 'CERTIFICATE' tls.cert | tr -d '=' | tr '/+' '_-'`"'&macaroon='"`base64 admin.macaroon | tr -d '=' | tr '/+' '_-'`" | tr -d '\n' | qrencode -o /tmp/out.png

**Comment by Satosh1Nakamot0** [comment]
L. Lightning Network - Mostrar LNDConnect Qr Ascii.
Añadir opción en el Menú.

Generate a QRCode or URI to connect applications to lnd instances.

lndconnect://<host>:<port>?[cert=<base64url DER certifcate>&]macaroon=<base64url macaroon>

Create and show a QR code using command line

This is useful when one doesn't want to bring dependencies.

echo 'lndconnect://example.com?cert='"`grep -v 'CERTIFICATE' tls.cert | tr -d '=' | tr '/+' '_-'`"'&macaroon='"`base64 admin.macaroon | tr -d '=' | tr '/+' '_-'`" | tr -d '\n' | qrencode -o /tmp/out.png
