### ISSUE TITLE
Api CoinGecko

### ISSUE THREAD

**Issue by Satosh1Nakamot0** [curly60e/pyblock#130]
Because we believe data should be democratized

100% Free crypto API
No keys required
Publicly available

CoinGecko API V3 https://coingecko.com/api/documentations/v3
Python https://github.com/man-c/pycoingecko
https://assets.coingecko.com/reports/API/CoinGecko-API-Deck.pdf

Access CoinGecko data such as live pricing, trading volume, tickers, exchanges, historical data, coin info & images, developer & community stats, events, global markets, and CoinGecko Beam coins & exchanges status updates directly.

Use our API to power your applications at no cost!
We would appreciate any link or mention of ‘Powered by CoinGecko API’ on your awesome application!

Note:
All our data is provided for free, and as-is without any warranty.
Timestamp returned by this API are in UTC Timezone.
You may refer to our branding guide as a reference.
For additional information about our API visit https://www.coingecko.com/api
Rate Limit: 100 requests/minute

Schemes
GET
/ping
Check API server status
simple

GET
/simple/price
Get the current price of any cryptocurrencies in any other supported currencies that you need.
GET
/simple/token_price/{id}
Get current price of tokens (using contract addresses) for a given platform in any other currency that you need.
GET
/simple/supported_vs_currencies
Get list of supported_vs_currencies.
coins

GET
/coins/list
List all supported coins id, name and symbol (no pagination required)
GET
/coins/markets
List all supported coins price, market cap, volume, and market related data
GET
/coins/{id}
Get current data (name, price, market, ... including exchange tickers) for a coin
GET
/coins/{id}/tickers
Get coin tickers (paginated to 100 items)
GET
/coins/{id}/history
Get historical data (name, price, market, stats) at a given date for a coin
GET
/coins/{id}/market_chart
Get historical market data include price, market cap, and 24h volume (granularity auto)
GET
/coins/{id}/market_chart/range
Get historical market data include price, market cap, and 24h volume within a range of timestamp (granularity auto)
GET
/coins/{id}/status_updates
Get status updates for a given coin (beta)
GET
/coins/{id}/ohlc
Get coin's OHLC (Beta)
contract

GET
/coins/{id}/contract/{contract_address}
Get coin info from contract address
GET
/coins/{id}/contract/{contract_address}/market_chart/
Get historical market data include price, market cap, and 24h volume (granularity auto) from a contract address
GET
/coins/{id}/contract/{contract_address}/market_chart/range
Get historical market data include price, market cap, and 24h volume within a range of timestamp (granularity auto) from a contract address
exchanges (beta)

GET
/exchanges
List all exchanges
GET
/exchanges/list
List all supported markets id and name (no pagination required)
GET
/exchanges/{id}
Get exchange volume in BTC and top 100 tickers only
GET
/exchanges/{id}/tickers
Get exchange tickers (paginated, 100 tickers per page)
GET
/exchanges/{id}/status_updates
Get status updates for a given exchange (beta)
GET
/exchanges/{id}/volume_chart
Get volume_chart data for a given exchange (beta)
finance (beta)

GET
/finance_platforms
List all finance platforms
GET
/finance_products
List all finance products
indexes (beta)

GET
/indexes
List all market indexes
GET
/indexes/{id}
get market index by id
GET
/indexes/list
list market indexes id and name
derivatives (beta)

GET
/derivatives
List all derivative tickers
GET
/derivatives/exchanges
List all derivative exchanges
GET
/derivatives/exchanges/{id}
show derivative exchange data
GET
/derivatives/exchanges/list
List all derivative exchanges name and identifier
status_updates (beta)

GET
/status_updates
List all status_updates with data (description, category, created_at, user, user_title and pin)
events

GET
/events
Get events, paginated by 100
GET
/events/countries
Get list of event countries
GET
/events/types
Get list of events types
exchange_rates

GET
/exchange_rates
Get BTC-to-Currency exchange rates
trending

GET
/search/trending
Get trending search coins (Top-7) on CoinGecko in the last 24 hours
global

GET
/global
Get cryptocurrency global data

**Comment by curly60e** [comment]
CoinGecko API agregada para la versión 0.7.0
