### ISSUE TITLE
PyBlock Sounds

### ISSUE THREAD

**Issue by Satosh1Nakamot0** [curly60e/pyblock#156]
Menú

Sound
-On
-Off

printf \\a and osascript -e beep play the default alert sound, but they are silent if the alert volume is set to zero. printf \\a is also silent if an audible bell is disabled.

You could also use afplay or say:

afplay /System/Library/Sounds/Funk.aiff
say done

There are more sound effect files in /System/Library/PrivateFrameworks/ScreenReader.framework/Versions/A/Resources/Sounds/.

You can use say -v ? (in Yosemite, at least) to get a list of voices installed -- I had several! Here's a little script to say what you want in every available voice: for i in $(say -v \? | awk '{print $1;}'); do echo $i; say -v $i "Build terminated\!"; done 

The simplest way is the use a bell echo -e "\a"
Another way is to echo ^G. But you don't literally type the ^G. Instead, type ctrl+v, ctrl+g, which will appear as echo ^G.
Another option, with less modifier keys, is to use the command tput bel.

The afplay command can also be used to play a specific sound file:

$ afplay /System/Library/Sounds/Funk.aiff 

Other
say beep

Sounds solo en los nuevos bloques por el momento.

**Comment by Satosh1Nakamot0** [comment]
Change Sound to Block Alarm

**Comment by Satosh1Nakamot0** [comment]
Other options

say New Block
say Satoshi Nakamoto
say PyBlock
say Knock knock, Neo

**Comment by Satosh1Nakamot0** [comment]
osascript -e 'beep'

osascript -e 'tell application "System Events" to beep'

printf "\a" also works in a terminal and will play the set alert sound.

**Comment by curly60e** [comment]
Para usar los sonidos utilizaré este pedazo de código así apicarlo en caso de usar otro sistema operativo.

from sys import platform
if platform == "linux" or platform == "linux2":
    # linux
elif platform == "darwin":          
    # OS X
elif platform == "win32":             
    # Windows...
