### ISSUE TITLE
PyBlock LNURL

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoin** [curly60e/pyblock#158]
LNURL is a bech32-encoded HTTPS/Onion query string which is supposed to help payer interact with payee and thus simplify a number of standard scenarios such as:

    Requesting incoming channels (LNURL-channel)
    Logging in (LNURL-auth)
    Withdrawing funds (LNURL-withdraw)
    Paying for a service (LNURL-pay)

An example LNURL:

    https://service.com/api?q=3fc3645b439ce8e7f2553a69e5267081d96dcd340693afabe04be7b0ccd178df

would be bech32-encoded as:

    LNURL1DP68GURN8GHJ7UM9WFMXJCM99E3K7MF0V9CXJ0M385EKVCENXC6R2C35XVUKXEFCV5MKVV34X5EKZD3EV56NYD3HXQURZEPEXEJXXEPNXSCRVWFNV9NXZCN9XQ6XYEFHVGCXXCMYXYMNSERXFQ5FNS

and presented in QR.

    If tag query parameter is present then this LNURL has a special meaning, further actions will be based on tag parameter value.
    Otherwise a GET request should be executed which must return a JSON object containing a tag field, further actions will be based on tag field value.

HTTPS or Onion

LNURL is acceptable in two forms: either an https:// clearnet link (no self-signed certificates allowed) or an http:// v2/v3 onion link.
Fallback scheme

LNURL can be used as fallback inside of other URI schemes, with the key 'lightning' and the value equal to the bech32-encoding.

Protocols

    [LNURL-channel](https://github.com/btcontract/lnurl-rfc/blob/master/lnurl-channel.md)
    [LNURL-auth](https://github.com/btcontract/lnurl-rfc/blob/master/lnurl-auth.md)
    [LNURL-withdraw](https://github.com/btcontract/lnurl-rfc/blob/master/lnurl-withdraw.md)
    [LNURL-pay](https://github.com/btcontract/lnurl-rfc/blob/master/lnurl-pay.md)

[Another LNURL](https://github.com/fiatjaf/awesome-lnurl)

**Comment by Satosh1Nakamot0** [comment]
https://lnurl.bigsun.xyz/

**Comment by curly60e** [comment]
Lo que mas me interesa de esto es el withdraw link.

**Comment by Satosh1Nakamot0** [comment]
> Lo que mas me interesa de esto es el withdraw link. 

Sí, withdraw es necesaria y Auth Para posibles futuras implementaciones en PyBLØCK puede ser muy interesante, por ejemplo, para login de users en ciertos menús más privados y que requieran de LNURL AUTH para poder acceder con tu propio nodo a funciones internas del mismo.
