### ISSUE TITLE
BWT in PyBlock

### ISSUE THREAD

**Issue by Satosh1Nakamot0** [curly60e/pyblock#171]
Bitcoin Wallet Tracker
bwt is a lightweight wallet xpub tracker and query engine for Bitcoin, implemented in Rust.

🔸 Personal HD wallet indexer (EPS-like)
🔸 Electrum RPC server (also available as a plugin!)
🔸 Developer-friendly, modern HTTP REST API
🔸 Real-time updates with Server-Sent-Events or Web Hooks

https://github.com/shesek/bwt

Full Server 1 https://github.com/shesek/bwt/releases/download/v0.1.5/bwt-0.1.5-x86_64-linux.tar.gz
Electrum Server 2 https://github.com/shesek/bwt/releases/download/v0.1.5/bwt-0.1.5-electrum_only-x86_64-linux.tar.gz
Electrum Plugin 3 https://github.com/shesek/bwt/releases/download/v0.1.5/bwt-0.1.5-electrum_plugin-x86_64-linux.tar.gz

$ wget https://github.com/shesek/bwt/releases/download/v0.1.5/bwt-0.1.5-x86_64-linux.tar.gz

# Verify signature
$ gpg --keyserver keyserver.ubuntu.com --recv-keys FCF19B67866562F08A43AAD681F6104CD0F150FC
$ wget -qO - https://github.com/shesek/bwt/releases/download/v0.1.5/SHA256SUMS.asc \
  | gpg --decrypt - | grep ' bwt-0.1.5-x86_64-linux.tar.gz$' | sha256sum -c -

$ tar zxvf bwt-0.1.5-x86_64-linux.tar.gz
$ ./bwt-0.1.5-x86_64-linux/bwt --xpub <xpub> ...

**Comment by curly60e** [comment]
Voy a chequear bien como funciona ya que está escrito en rust, en su mayoría.

**Comment by Satosh1Nakamot0** [comment]
Install Cargo on Mac OSX

About the App

    App name: Cargo
    App description: cargo (App: Not Available)
    App website: https://crates.io/

Install the App

    Press Command+Space and type Terminal and press enter/return key.
    Run in Terminal app:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null ; brew install caskroom/cask/brew-cask 2> /dev/null
    and press enter/return key.
    If the screen prompts you to enter a password, please enter your Mac's user password to continue. When you type the password, it won't be displayed on screen, but the system would accept it. So just type your password and press ENTER/RETURN key. Then wait for the command to finish.
    Run:
    brew cask install cargo

Done! You can now use Cargo.
