### ISSUE TITLE
Add Wander Terminal

### ISSUE THREAD

**Issue by curly60e** [curly60e/pyblock#249]
Add this feature:

https://github.com/pxsocs/warden_terminal

Maybe for v0.9.2-3

**Comment by pxsocs** [comment]
Happy to help. The [data.py](https://github.com/pxsocs/warden_terminal/blob/master/data.py) file contains most of the data gathering methods. For example:
```
python3 data.py data_btc_price
```
Will output the Bitcoin Price Data.

**Comment by curly60e** [comment]
> Happy to help. The [data.py](https://github.com/pxsocs/warden_terminal/blob/master/data.py) file contains most of the data gathering methods. For example:
> 
> ```
> python3 data.py data_btc_price
> ```
> 
> Will output the Bitcoin Price Data.

On what line of data.py can I call directly from the code? Don't want to call it from shell.

**Comment by curly60e** [comment]
> > Happy to help. The [data.py](https://github.com/pxsocs/warden_terminal/blob/master/data.py) file contains most of the data gathering methods. For example:
> > ```
> > python3 data.py data_btc_price
> > ```
> > 
> > 
> > Will output the Bitcoin Price Data.
> 
> On what line of data.py can I call directly from the code? Don't want to call it from shell.

Will add your project into mine in another folder if you agree, of course?

**Comment by pxsocs** [comment]
Depends how you'd like to make the call. 
But you could, for example:

![image](https://user-images.githubusercontent.com/40473443/101993370-cf90c900-3c98-11eb-8149-49ccdfa7137a.png)

This returns the ANSI table

**Comment by pxsocs** [comment]
Absolutely fine to include, modify, delete...

**Comment by curly60e** [comment]
> Depends how you'd like to make the call.
> But you could, for example:
> 
> ![image](https://user-images.githubusercontent.com/40473443/101993370-cf90c900-3c98-11eb-8149-49ccdfa7137a.png)
> 
> This returns the ANSI table

Looks awesome!! Great job! Will do this.

**Comment by curly60e** [comment]
> Absolutely fine to include, modify, delete...

Do you have an ANSI logo or do you want I make one for you? Can do lot of desings with python-cfonts.

**Comment by pxsocs** [comment]
You can use the one in the [repository (welcome.py)](https://github.com/pxsocs/warden_terminal/blob/master/welcome.py)

**Comment by pxsocs** [comment]
Need to test this in other terminals, BTW. Only tested on Mac but will soon test on some of my nodes running different os / screens.

**Comment by curly60e** [comment]
Cool! Will use that logo!

**Comment by curly60e** [comment]
![image](https://user-images.githubusercontent.com/55191248/101995363-1e922a80-3ca8-11eb-8fa4-82b812ce93df.png)
![image](https://user-images.githubusercontent.com/55191248/101995375-2d78dd00-3ca8-11eb-9f9e-2bf7b467b7c5.png)

Testing

**Comment by curly60e** [comment]
```
def callGitWardenTerminal():
    if os.path.isdir('warden_terminal'):
        os.system("cd warden_terminal && python3 node_warden.py")
    else:
        git = "git clone https://github.com/pxsocs/warden_terminal.git"
        os.system(git)
        os.system("cd warden_terminal && python3 node_warden.py")
```

Simple solution and the user can explore the hole program.

**Comment by curly60e** [comment]
> ```
> def callGitWardenTerminal():
>     if os.path.isdir('warden_terminal'):
>         os.system("cd warden_terminal && python3 node_warden.py")
>     else:
>         git = "git clone https://github.com/pxsocs/warden_terminal.git"
>         os.system(git)
>         os.system("cd warden_terminal && python3 node_warden.py")
> ```
> 
> Simple solution and the user can explore the hole program.

```
def callGitWardenTerminal():
    if not os.path.isdir('warden_terminal'):
        git = "git clone https://github.com/pxsocs/warden_terminal.git"
        os.system(git)
    os.system("cd warden_terminal && python3 node_warden.py")
```

Better

**Comment by Satosh1Nakamot0** [comment]
The Easter Egg in @_PyBLOCK_:

“The WARden Terminal.”
By @AlphaaZeta.

Now need 1 new module.

Install it:
a@A:~> sudo pip3 install pyfiglet
