### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by danvergara** [curly60e/pyblock#318]
**Is your feature request related to a problem? Please describe.**

The other day I tried to install the project on my node, following the installation guide and found the process a bit frustrating because I tried to set up an virtual environment to isolate the installation and its dependencies (to avoid conflicts with other python tools that I use in my node), and for tools like poetry or pipenv is hard to figure out a graph of dependencies without end up with bunch of version conflicts. Had to tweak the requirements.txt a little bit myself to make it work. 

**Describe the solution you'd like**

I think tools like poetry or pipenv might be a good addition to the project along with the proper instructions on to install de dependecies using such tools.

**Describe alternatives you've considered**

As I said, I considered poetry and pipenv as dependency resolution tools, I prefer poetry because it is in active development and maintenance.

**Additional context**

**Comment by danvergara** [comment]
Besides that, I didn't find a .gitignore file, wihch is very useful at the time to have a clean development environment.

**Comment by curly60e** [comment]
Thanks for sharing this information, I will take note of this issue and also checkout your pullrequest. :)

**Comment by danvergara** [comment]
Awesome, if you have questions, don't hesitate to ask. I like this tool a lot.
